"""Provisional MidEx instrument and observational settings."""

import copy
import lenstronomy.Util.util as util

__all__ = ["MidEx"]

# --- PLACEHOLDER VALUES ---
# Update these dictionaries with your actual MidEx instrument specifications.
A_band_obs = {
    "exposure_time": 90.0,
    "sky_brightness": 22.0,
    "magnitude_zero_point": 26.0,
    "num_exposures": 50,
    "seeing": 0.5,
    "psf_type": "GAUSSIAN",
}

B_band_obs = {
    "exposure_time": 90.0,
    "sky_brightness": 21.5,
    "magnitude_zero_point": 26.0,
    "num_exposures": 50,
    "seeing": 0.5,
    "psf_type": "GAUSSIAN",
}

C_band_obs = {
    "exposure_time": 90.0,
    "sky_brightness": 21.0,
    "magnitude_zero_point": 26.0,
    "num_exposures": 50,
    "seeing": 0.5,
    "psf_type": "GAUSSIAN",
}

D_band_obs = {
    "exposure_time": 90.0,
    "sky_brightness": 20.5,
    "magnitude_zero_point": 26.0,
    "num_exposures": 50,
    "seeing": 0.5,
    "psf_type": "GAUSSIAN",
}

class MidEx(object):
    """Class contains MidEx instrument and observation configurations."""

    def __init__(self, band="A", psf_type="GAUSSIAN", coadd_years=10):
        """
        :param band: string, 'A', 'B', 'C', or 'D' supported. Determines obs dictionary.
        :param psf_type: string, type of PSF ('GAUSSIAN' supported).
        :param coadd_years: int, number of years corresponding to num_exposures in obs dict. Currently supported: 1-10.
        """
        # Ensure the band is uppercase for MidEx
        if band.isalpha():
            band = band.upper()
            
        if band == "A":
            self.obs = copy.deepcopy(A_band_obs)
        elif band == "B":
            self.obs = copy.deepcopy(B_band_obs)
        elif band == "C":
            self.obs = copy.deepcopy(C_band_obs)
        elif band == "D":
            self.obs = copy.deepcopy(D_band_obs)
        else:
            raise ValueError(
                "band %s not supported! Choose 'A', 'B', 'C', or 'D'." % band
            )

        if psf_type != "GAUSSIAN":
            raise ValueError("psf_type %s not supported!" % psf_type)

        if coadd_years > 10 or coadd_years < 1:
            raise ValueError(
                " %s coadd_years not supported! Choose an integer between 1 and 10."
                % coadd_years
            )
        elif coadd_years != 10:
            self.obs["num_exposures"] = coadd_years * self.obs["num_exposures"] // 10

        # --- PLACEHOLDER CAMERA SPECS ---
        self.camera = {
            "read_noise": 5.0,     # std of noise generated by read-out (in units of electrons)
            "pixel_scale": 0.15,   # scale (in arcseconds) of pixels
            "ccd_gain": 2.0,       # electrons/ADU (analog-to-digital unit)
        }

    def kwargs_single_band(self):
        """
        :return: merged kwargs from camera and obs dicts
        """
        kwargs = util.merge_dicts(self.camera, self.obs)
        return kwargs